apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wisecow-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/nightfury000/manifest-repo.git 
    targetRevision: HEAD
    path: ./applications/wisecow-app
  destination:
    server: https://kubernetes.default.svc
    namespace: wisecow-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
